# Generated by Django 3.0.5 on 2021-12-12 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_auto_20211212_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={},
        ),
    ]